steps:
  # Docker 이미지 빌드
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/vona-server:$COMMIT_SHA', '.']

  # 빌드된 이미지를 Container Registry에 푸시
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/vona-server:$COMMIT_SHA']

  # Cloud Run에 서비스 배포
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'vona-server'
      - '--image=gcr.io/$PROJECT_ID/vona-server:$COMMIT_SHA'
      - '--region=asia-northeast3' # 실제 사용 지역으로 변경
      - '--platform=managed'
      - '--allow-unauthenticated' # 필요시 포함 또는 제거
      - '--timeout=300s' # 요청 타임아웃 5분으로 설정
      - '--cpu=1' # CPU 할당
      - '--memory=512Mi' # 메모리 할당
      - '--min-instances=0' # 최소 인스턴스 수
      - '--max-instances=10' # 최대 인스턴스 수
      - '--port=8080' # 포트 명시적 지정
      - '--set-env-vars=NODE_ENV=production' # 환경 변수 설정
      - '--startup-cpu-boost' # 시작 시 CPU 부스트 활성화

# 이미지 태그
images:
  - 'gcr.io/$PROJECT_ID/vona-server:$COMMIT_SHA'

# 서비스 계정을 최상위 필드로 이동
serviceAccount: '307101842878-compute@developer.gserviceaccount.com'

options:
  logging: CLOUD_LOGGING_ONLY
  # 동시성 제한
  machineType: 'E2_HIGHCPU_8'

timeout: '1200s' # 20분 타임아웃
