steps:
  # Docker 이미지 빌드
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/vona-server:$COMMIT_SHA', '.']

  # 빌드된 이미지를 Container Registry에 푸시
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/vona-server:$COMMIT_SHA']

  # Cloud Run에 서비스 배포 (동적으로 환경 변수 적용)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'vona-server'
      - '--image=gcr.io/$PROJECT_ID/vona-server:$COMMIT_SHA'
      - '--region=asia-northeast3'
      - '--platform=managed'
      - '--allow-unauthenticated'

# 이미지 태그
images:
  - 'gcr.io/$PROJECT_ID/vona-server:$COMMIT_SHA'

# 서비스 계정을 최상위 필드로 이동
serviceAccount: '307101842878-compute@developer.gserviceaccount.com'

options:
  logging: CLOUD_LOGGING_ONLY

timeout: '1600s' # 26분 타임아웃
