steps:
  # Docker 이미지 빌드
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/vona-server:$COMMIT_SHA', '.']

  # 빌드된 이미지를 Container Registry에 푸시
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/vona-server:$COMMIT_SHA']

  # Cloud Run에 서비스 배포
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'vona-server'
      - '--image=gcr.io/$PROJECT_ID/vona-server:$COMMIT_SHA'
      - '--region=asia-northeast3' # 실제 사용 지역으로 변경
      - '--platform=managed'
      - '--allow-unauthenticated' # 필요시 포함 또는 제거

# 이미지 태그
images:
  - 'gcr.io/$PROJECT_ID/vona-server:$COMMIT_SHA'

options:
  serviceAccount: '307101842878-compute@developer.gserviceaccount.com'
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s' # 20분 타임아웃
